---
title: "R Notebook"
output: html_notebook
---



```{r}
# Définit le projet root comme base pour tous les chunks
knitr::opts_knit$set(root.dir = rprojroot::find_root(rprojroot::has_file("my_project.Rproj")))
knitr :: opts_knit$get("root.dir")

set.seed(123)
```


```{r}
library(pacman)
p_load(Seurat,SeuratData,Matrix,dplyr,DropletUtils,presto,gprofiler2,ggplot2,patchwork,gplots,cowplot,gprofiler2,openxlsx, )
```


```{r}
###integration with seurat of two data set:Integration of single-cell sequencing datasets, for example across experimental batches, donors, or conditions, is often an important step in scRNA-seq workflows. Integrative analysis can help to match shared cell types and states across datasets, which can boost statistical power, and most importantly, facilitate accurate comparative analysis across datasets
```

```{r}
##import the two seurat ojbect and combine them in one 

# 1. Load your two Seurat objects
srat_filt <- readRDS("outputs/exp1/rds/Example_srat_filt_exp1.RDS")
sob_filt <- readRDS("outputs/exp2/rds/Example_sob_filt_exp2.RDS")

```


```{r}
##add a batch method label
srat_filt$Method = "srat"
sob_filt$Method = "sob"
```


```{r}
###merge the two object: make the same cells in both seurat object unique like
#a1 and a2
obj = merge(srat_filt, y= sob_filt)
```
```{r}
##split RNA assay into layers: can skipp this part , already done on the merge

obj[["RNA"]] = split(obj[["RNA"]], f = obj$Method) :pour un seul objet seurat , pour ce cas no

```


```{r}
obj = NormalizeData(obj)
obj = FindVariableFeatures(obj)
obj = ScaleData(obj)
obj = RunPCA(obj)
```
```{r}
##visualize the result without integration:cells are grouping by cell type 
obj = FindNeighbors(obj, dims= 1:30, reduction =  "pca")
obj = FindClusters(obj, resolution = 2, cluster.name = "unintegrated_clusters")
```

```{r, fig.width = 12}
obj = RunUMAP(obj, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")

#visualize by batch and cell type annotation 
DimPlot(obj, reduction = "umap.unintegrated", group.by = c("Method", "celltype_label"), shuffle=T)
```

```{r}
###NOW PERFORM INTEGRATIVE ANALYSIS , method:

```


```{r}
##1-Harmony (method=HarmonyIntegration): for larger dataset: just this one work

Reductions(obj) #check pca
#if not:
obj <- RunPCA(obj, verbose = TRUE)

##harmony integration:work
obj =IntegrateLayers(
  object = obj, method = HarmonyIntegration,
  orig.reduction = "pca", new.reduction = "harmony",
  verbose = F
)

```

```{r}
#next for visualization
obj <- FindNeighbors(obj, reduction = "harmony", dims = 1:30)
obj <- FindClusters(obj, resolution = 2, group.name = "harmony_clusters")
```


```{r}
##plot
colnames(obj@meta.data) #check colname
obj = RunUMAP(obj, reduction = "harmony",dims = 1:30)

p1 = DimPlot(
  obj, 
  reduction = "umap",
  group.by = c("Method", "nCount_RNA", "nFeature_RNA", "seurat_clusters"),
  combine = FALSE,
  label.size = 2
)
##return the list of ggplts objects
```


```{r}
##return the list of ggplts objects
p1[4]
```


```{r}
##2CCAINTEGRATION: not working
obj <- IntegrateLayers(
  object = obj,
  method = CCAIntegration,
  orig.reduction = "pca",
  new.reduction = "integrated.cca",
  verbose = FALSE
)

```


```{r}
##3:SeuratWrappers package or python
obj <- IntegrateLayers(
  object = obj, method = scVIIntegration,
  new.reduction = "integrated.scvi",
  conda_env = "../miniconda3/envs/scvi-env", verbose = FALSE
)
```


```{r}
##4: need SeuratWrappers library
obj <- IntegrateLayers(
  object = obj, method = FastMNNIntegration,
  new.reduction = "integrated.mnn",
  verbose = FALSE
)


```


```{r}
##5
# Make sure globals size is sufficient
options(future.globals.maxSize = 2 * 1024^3)  # 2 GB

 #Run RPCA integration
obj_rpca <- IntegrateLayers(
  object = obj,                     # use the Seurat object with PCA
  method = RPCAIntegration,
  orig.reduction = "pca",           # must exactly match Reductions(obj)
  new.reduction = "integrated.rpca",
  verbose = FALSE
)
```

```{r}
##another option
# Increase parallel globals size for large datasets
options(future.globals.maxSize = 3 * 1024^3)  # 3 GB

# SCTransform normalization
obj <- SCTransform(obj, verbose = FALSE)

# PCA (required for RPCAIntegration)
obj <- RunPCA(obj, npcs = 30, verbose = FALSE)

# Check PCA exists
Reductions(obj)  # Should include "pca"

obj <- IntegrateLayers(
  object = obj,
  method = RPCAIntegration,
  normalization.method = "SCT",
  new.reduction = "integrated.rpca",  # clearer name than integrated.dr
  verbose = FALSE
)



```

```{r}
# UMAP using the integrated reduction
obj <- RunUMAP(obj, reduction = "integrated.rpca", dims = 1:30)

# Neighbors & clustering
obj <- FindNeighbors(obj, reduction = "integrated.rpca", dims = 1:30)
obj <- FindClusters(obj, resolution = 2)

# Visualize
DimPlot(obj,
        reduction = "umap",
        group.by = "Method"
        )          # batch check
```
```{r}

DimPlot(
  obj,
  reduction = "umap",
  group.by = "seurat_clusters",
  label = FALSE,  # remove cluster numbers from plot
  pt.size = 0.5
) + 
theme(
  legend.position = "top",
  legend.box.margin = margin(0, 0, 0, 0),
  plot.margin = margin(10, 10, 10, 10),
  legend.spacing.x = unit(2, "cm"),
  legend.text = element_text(size = 10, color = "black"),
  legend.title = element_text(size = 8)
)
```

```{r}

# Compute majority cell type for each cluster
cluster2type <- obj@meta.data %>%
  group_by(seurat_clusters) %>%
  summarize(celltype = names(sort(table(cell_type), decreasing = TRUE)[1]))

# Convert to named vector
cluster2type_vec <- setNames(cluster2type$celltype, cluster2type$seurat_clusters)

# Create a new column with meaningful labels
obj$celltype_label <- plyr::mapvalues(
  x = obj$seurat_clusters,
  from = names(cluster2type_vec),
  to = cluster2type_vec
)

```




```{r}


DimPlot(
  obj,
  reduction = "umap",
  group.by = "celltype_label",  # use meaningful names
  label = FALSE,                # no text on the plot itself
  pt.size = 0.5
) + 
theme(
  legend.position = "top",
  legend.box.margin = margin(0, 0, 0, 0),
  plot.margin = margin(10, 10, 10, 10),
  legend.spacing.x = unit(2, "cm"),
  legend.text = element_text(size = 10, color = "black"),
  legend.title = element_text(size = 8)
)

```



```{r}
Reductions(obj)
```



```{r}
# List all features in the active assay
head(rownames(obj[["SCT"]]))    # or obj[["RNA"]] if you want RNA assay


```




```{r}
##Find neighbors & clusters on RPCA reduction

# Use the RPCA integrated reduction
obj <- FindNeighbors(obj, reduction = "integrated.rpca", dims = 1:30)

# Cluster the cells
obj <- FindClusters(obj, resolution = 1, verbose = FALSE)

# Save as integrated_clusters
obj$integrated_clusters <- obj$seurat_clusters




```




```{r}

##plots markers genes

##select top markers

top_markers <- cluster_markers %>%
  group_by(cluster) %>%
  top_n(n = 3, wt = avg_log2FC)   # top 3 markers per cell type


my_markers <- c("GZMB", "GZMH", "CDH6",  "SLC38A11")

plots <- lapply(my_markers, function(gene) {
  VlnPlot(
    obj,
    features = gene,
    group.by = "integrated_clusters",
    pt.size = 0,
    log = TRUE
  ) + NoLegend() + ggtitle(gene)
})

wrap_plots(plots, ncol = 2)

```
```{r}
# UMAP on RPCA-integrated PCA
obj <- RunUMAP(
  obj,
  reduction = "integrated.rpca",  # the RPCA-integrated reduction
  dims = 1:30,
  reduction.name = "umap.rpca"
)


```



```{r}

# UMAP on the original PCA before integration
obj <- RunUMAP(
  obj,
  reduction = "pca",
  dims = 1:30,
  reduction.name = "umap.unintegrated"
)
```

```{r}
##visialize

p_unint <- DimPlot(
  obj,
  reduction = "umap.unintegrated",
  group.by = "seurat_clusters"  # your original cluster numbers
)

p_rpca <- DimPlot(
  obj,
  reduction = "umap.rpca",
  group.by = "seurat_clusters"  # same clusters, now in integrated space
)

# Combine plots side by side
p_unint | p_rpca


```

```{r}
#Once integrative analysis is complete, you can rejoin the layers - which collapses the individual datasets together and recreates the original counts and data layers. You will need to do this before performing any differential expression analysis. However, you can always resplit the layers in case you would like to reperform integrative analysis.

class(obj)
Layers(obj)
obj <- JoinLayers(obj) #dont need it here , data already collapsed.
obj

#if we want to go back for others integration :
#Resplitting layers
obj[["RNA"]] <- SplitLayer(obj[["RNA"]], f = obj$Method)

```



```{r}
saveRDS(
  obj, 
  file = "/Users/aminatasouleymanesow/Desktop/my_project/Example_sob_srat.RDS"
)
## run it later to load all 
obj<- readRDS("/Users/aminatasouleymanesow/Desktop/my_project/Example_sob_srat.RDS")
```

