---
title: "R Notebook"
output: html_notebook
---




```{r}
# Définit le projet root comme base pour tous les chunks
knitr::opts_knit$set(root.dir = rprojroot::find_root(rprojroot::has_file("my_project.Rproj")))
knitr :: opts_knit$get("root.dir")
set.seed(123)
```


```{r setup, include=FALSE}
library(pacman)
p_load(Seurat,SeuratData,Matrix,dplyr,DropletUtils,presto,gprofiler2,ggplot2,patchwork,gplots,cowplot,gprofiler2,openxlsx)
```

```{r}
###load the data together
exp <- readMM("data/raw/exp1/matrix.mtx.gz")
bc  <- read.delim("data/raw/exp1/barcodes.tsv.gz", header = FALSE)
g   <- read.delim("data/raw/exp1/features.tsv.gz", header = FALSE)
dim(exp)

```



```{r,fig.width=11, fig.height=4}
#detection of empty droplets: cellranger or algorithm, already done
iscell_dd = defaultDrops(exp, expected = 5000)

meta = data.frame(row.names = bc$V1, iscell_dd = iscell_dd)

# empty drops algorithm - alternative to the default algorithm but also slower
eout = emptyDrops(exp, lower = 200) # should take 5-10min
eout$FDR[is.na(eout$FDR)] = 1 # needs some correction on NA values
iscell_ed = eout$FDR<=0.01 # thresholding based on adjusted p-value
```



```{r}
#assigne row and colnames
colnames(exp) = bc$V1
rownames(exp) = g$V2
##make the analysis easy
```


```{r}
##reduce the size of expected

#cell that have at least one count
cellcond=colSums(exp) > 0 

#keep genes that are expressed inn at least one cell
genecond=rowSums(exp) > 0

#subsets the matrix
exp= exp[genecond,cellcond] #remove genes that have nothing to contribute
dim(exp)
```

```{r}
##create the seuratobject
rownames(exp) <- make.unique(rownames(exp))

srat=CreateSeuratObject(counts=exp, project = "MyProject")
```

```{r}
##quality control:QC
srat=PercentageFeatureSet(srat, col.name = "percent.mt",assay = "RNA", pattern = "^MT-")
```

```{r}
VlnPlot(srat,features = c("nCount_RNA","nfeature_RNA","percent.mt" ), ncol=3, log= TRUE) #pt.size=0: can add this if we dont want the dot in the plot
# without log the expression is hard to see
```

```{r,fig.width=10, fig.height=3.5}
#scarletsplots
plot1=FeatureScatter(srat,feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2=FeatureScatter(srat, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
```

```{r}
##apply  filter QC to 
qcthr= c(
  "maxMT"=15,         #mitochondrial reads
  "minC"=1000,        #min counts per cells
  "minG"=750,         # min genes per cells
  "maxC"=50000,        #max count per cells
  "maxG"=6000)        #max genes per cells

cells=srat$percent.mt < qcthr["maxMT"] &
      srat$nCount_RNA > qcthr["minC"] &
      srat$nCount_RNA < qcthr["maxC"] &
      srat$nFeature_RNA > qcthr["minG"] &
      srat$nFeature_RNA < qcthr["maxG"]
srat_filt=subset(srat,cells=colnames(srat) [cells])
```

```{r}
#normalization
srat_filt= NormalizeData(srat_filt,normalization.method = "LogNormalize", scale.factor=10000)
```
```{r}
#select the highly variable genes
srat_filt=FindVariableFeatures(srat_filt, selection.method = "mean.var.plot",
                               num.bin = 30, binning.method = "equal_frequency",
                               nfeatures = 50000, mean.cutoff = c(0.01, 10),
                               dispersion.cutoff = c(0.01, Inf))
print(length(VariableFeatures(srat_filt)))
```


```{r}
#top 5000
srat_filt=FindVariableFeatures(srat_filt,selection.method = "vst",
                               nfeatures = 5000)
print(length(VariableFeatures(srat_filt)))
```
```{r,fig.width=10, fig.height=10}
## check HGV
#20 most HGV
top20=head(VariableFeatures(srat_filt), 20)

#plot VF with and  without labels
plot1= VariableFeaturePlot(srat_filt)
plot2= LabelPoints(plot=plot1, points=top20,xnudge = 0,ynudge = 0 ,repel= TRUE)
plot2
#xnudge and ynudge to 0 for optimal results
```
```{r}
##Scalling the data
#make gene in same levels
srat_filt=ScaleData(srat_filt, vars.to.regress = c("nCount_RNA"),
                    do.scale = F, verbose=T)
```
```{r}
## SCTransform: another normalization method
srat_filt=SCTransform(srat_filt, do.correct.umi = T, verbose = F,
                      vars.to.regress = "nCount_RNA",
                      variable.features.rv.th= 1,variable.features.n = NULL,
                      seed.use=1)
```

```{r}
##compare the intersection of HVG
DefaultAssay(srat_filt)= "SCT"
list_hvg=list("RNA" = VariableFeatures(srat_filt, assay = "RNA"),
              "SCT" = VariableFeatures(srat_filt, assay="SCT"))

gplots::venn(list_hvg)
```
```{r}
##PCA in seurat
dim(srat_filt)

srat_filt= RunPCA(srat_filt, verbose = T, assay="SCT", npcs = 50)
#plot
DimPlot(srat_filt, reduction = "pca", dims = c(1,2))
```
```{r}
##biological variability
VizDimLoadings(srat_filt, dims = 1:3, reduction = "pca", ncol=3)
```
```{r,fig.width=8, fig.height=10}
srat_filt[["pca"]]

DimHeatmap(srat_filt, reduction= "pca",assays = "SCT", dims = 1:10,
           cells = 500, balanced = TRUE, ncol = 3)
```

```{r}
##check contribution of PCA:help to select how many PCA are important to carry for later analysis
ep=ElbowPlot(srat_filt, ndims = 50)
print(ep)
```

```{r}
##Dimensionality reduction:t-SNE,UMAP
ncomp=15 #number of pca we want
srat_filt=RunUMAP(srat_filt,  dims=1:ncomp  ,   verbose = F)
srat_filt=RunTSNE(srat_filt,  dims=1:ncomp  ,  verbose = F)

#plots

DimPlot(srat_filt, reduction = "umap")
```

```{r}
DimPlot(srat_filt, reduction = "tsne")
# just serve to represent data's variability in   2D
```
```{r}
##clustering:plots to determine which cells are more similar to which.

red="pca"
srat_filt=FindNeighbors(
  srat_filt,
  dims = 1:ncomp, 
  verbose=T,
  reduction = red,
  graph.name = paste0(red, ncomp))
```
```{r}
srat_filt=FindClusters(srat_filt,algorithm = 2, verbose = T,
                       graph.name = paste0(red,ncomp),
                       resolution = seq(0.2,1,0.1))
##This command runs graph-based clustering of your cells using 15 PCs.
#It tests multiple resolutions (0.2 → 1.0) so you can later decide how many clusters make sense.
```
```{r}
# setting a more sensible identity as default
srat_filt=SetIdent(srat_filt, value = paste0(red, ncomp, "_res.0.3"))
head(srat_filt)
```

```{r,fig.width=10, fig.height=10}
#have a look in clustering resolutions
plt_list=list()

#iterate each clustering resolution
head(srat_filt@meta.data)

for(cl in colnames(srat_filt@meta.data)[grepl("pca15_", colnames(srat_filt@meta.data))]){
srat_filt = SetIdent(srat_filt, value = cl) # set the resolution as default identity
plt_list[[cl]] = DimPlot(srat_filt, reduction = "umap", 
                         label = T, raster = F, pt.size = 0.2, shuffle = T)+
    labs(subtitle = cl)+
    theme(legend.position = "none",
          aspect.ratio = 1)
}
##check the clustering type
colnames(srat_filt@meta.data)

#plot
cowplot::plot_grid(plotlist = plt_list,ncol = 3)
```
```{r}
##characterizations groups of cells
#real cells populations
#genes to pick
FeaturePlot(srat_filt, features = c("PTPRC"))

#visualize the expression of a specific genes(PTPRC)
```
```{r}
##calculate the marker genes for a choosen clustering resolution
#table(Idents(srat_filt))

#table(srat_filt[[cl_use]]) #return that all cells are in one cluster

cl_use= "pca15_res.1" #cluster with hight resolution
srat_filt=SetIdent(srat_filt, value = cl_use)
mk_clusters= wilcoxauc(srat_filt, group_by = cl_use, seurat_assay = "SCT") #a table markers genes foe all clusters
#

xxx = mk_clusters |>
  filter(padj<=0.05) |>
  filter(logFC>0.2)
xxx$group = factor(xxx$group)

mk_clusters |>
  group_by(group) |> # for each cluster
  filter(padj<=0.05) |> # only p-value below 0.05
  top_n(n = 3, wt = logFC) # top genes per cluster, ranked by logFC
```

```{r}
## alternative built in Seurat (slower!) (although Seurat now also ships presto)
#mk_clusters = FindAllMarkers(srat_filt, assay = "SCT", test.use = "wilcox",
#                             pseudocount.use = 0.1, logfc.threshold = 0.2, verbose = T)
##View(mk_clusters[mk_clusters$padj<=0.05,])

#we just have one cluster so cannot find the marker 
```

```{r}
##look top genes in UMAP
top_genes= mk_clusters %>%
  filter(group==0) %>%
  arrange(desc(auc))%>%
  head(5) %>%
  pull(feature)

##

FeaturePlot(srat_filt, features = top_genes, reduction = "umap") #genes  name for argument, visualize gene expression on UMAP, Dimplot for clusters
# or per cluster
```

```{r}
VlnPlot(srat_filt, features = top_genes, group.by = cl_use)
```
```{r}
##compare pairs of cell populations (1 vs 1 comparison º~)
#we find markers genes between cluster 4 and 5
mk45 = FindMarkers(srat_filt, ident.1 = "4", ident.2 = "5", assay = "SCT", 
                   test.use = "wilcox", pseudocount.use = 0.1, logfc.threshold = 0.2)
#top markers
top_genes= mk45 %>%
  arrange(desc(avg_log2FC)) %>%
  head(5) %>%
  rownames()
head(top_genes)

#give name to cell types:


##plolt markers
FeaturePlot(srat_filt, features = top_genes, reduction = "umap", pt.size = 0.3)
```
```{r}
p1 <- DimPlot(srat_filt, reduction = "umap", label = TRUE)
p2 <- FeaturePlot(srat_filt, features = top_genes[4], reduction = "umap")

plot_grid(p1, p2, ncol = 2)
```

```{r}
##not include just a not
##function foe subcluster from cluster: my personal preference is to not simply subset and cluster, but rather recalculate HVG, PCA, and NN graph for the cell subset. This is because we might find that the initial set of HVG/PCs does not reflect their variability.

##find the argument we have on r 
?FindSubCluster
# or
args(FindSubCluster)
```

```{r}
srat_filt=FindSubCluster(srat_filt, cluster = "6", graph.name= paste0(red,ncomp))
table(srat_filt@meta.data$sub.cluster)
```

```{r}
##score groups of cells based on cell cycle for stem cell population
srat_filt = CellCycleScoring(srat_filt, 
                             s.features = cc.genes$s.genes, 
                             g2m.features = cc.genes$g2m.genes, 
                             set.ident = F,
                             nbin = 20)
DimPlot(srat_filt, reduction = "umap", group.by = "Phase")
```
```{r}
##or just plotting for cell populations
FeaturePlot(srat_filt, features = c("TOP2A", "MKI67", "CDK1"))
```


```{r}
##find gene ontology terms and pathway in marker genes
# markers for cluster x
degenes = mk_clusters %>%
  filter(group=="3" & padj<=0.05 & logFC>0.2) %>%
  arrange(-logFC)
allgenes = rownames(srat_filt) # all genes, to serve as background

gprof_enr = gost(degenes$feature, ordered_query = T, 
                 custom_bg = allgenes, # always set a custom bg!
                 organism = "hsapiens") # what is the organism?

head(gprof_enr$result)
View(gprof_enr$result)
```

```{r}
##meaning of genes names  that caracterize each cluster1
#go back to the code find marker for cluster(the previous ) and change the number in filter group
cl1_genes = xxx[order(xxx$logFC, decreasing = T),]
cl1_genes = cl1_genes$feature[cl1_genes$group=="1"][1:30]
cl1_genes
```

```{r}
###Now see the meaning for each cells in clusters
##option2
library(dplyr)
library(gprofiler2)
#check the clusters individually to know which is empty or not
table(mk_clusters$group[mk_clusters$padj <= 0.1 & mk_clusters$logFC > 0.2])

 
# Prepare genes list per cluster
filtered_clusters <- mk_clusters %>%
  filter(padj <= 0.1 & logFC > 0.2) %>%
  arrange(desc(logFC))
#convert each cluster into a vector of genes
cluster_genes_list=split(filtered_clusters, f=filtered_clusters$group)

# Convert cluster into vector of gene names
cluster_genes_list <- lapply(cluster_genes_list, function(df) df$feature)

# Check how many genes per cluster passing the filter
sapply(cluster_genes_list, length)
  
#enrichment per cluster
all_results_go=list()

for( clust in names(cluster_genes_list)) {
  degenes=cluster_genes_list[[clust]]
  n_genes=length(degenes)
  cat("RUNNING GO for cluster:",clust,"-Genes:",n_genes,"\n")
  
  #skip if no genes in cluster
  if (n_genes==0) {
    cat("No genes for cluster", clust,"\n\n")
    next
  }
  #profiler enrichment
  gostres=gost(
    query=degenes,
    custom_bg= rownames(srat_filt),
    organism= "hsapiens",
    sources=c("GO:BP"),
    significant= TRUE
  )
  
  #filter and store top results
  if(!is.null(gostres$result) && nrow(gostres$result) > 0) {
    filtered=gostres$result %>%
      filter(p_value < 0.05) %>%
      select(term_name,source, p_value) %>%
      arrange(p_value) %>%
      head(5)
    
    if(nrow(filtered) > 0) {
      
    filtered$cluster=clust
    all_results_go[[clust]]= filtered
    
    cat("==Cluster", clust,"==\n")
    print(filtered)
    cat("\n")
    
  } else {
    cat("No significant terms for cluster", clust,"\n\n")  
  }
    
 }  else {
    cat("no enrichment results for cluster", clust,"\n\n")
 }  
}

#combine all in a table
all_results_go_df=bind_rows(all_results_go)

#see
head(all_results_go_df)
View(all_results_go_df)
#save in excel

```

```{r}
##reorder the files

#convert cluster col to numeric
all_results_go_df$cluster= as.numeric(all_results_go_df$cluster)

#reorder in asc
all_results_go_df=all_results_go_df%>%
  arrange(cluster)
View(all_results_go_df)

# save in excel
#use csv2 for nice output
write.csv2(
  all_results_go_df,
  file = "/Users/aminatasouleymanesow/Desktop/my_project/outputs/exp1/tables/cluster_GO_BP_enrichment_sorted.csv",
  row.names = FALSE,
  fileEncoding = "UTF-8"
)

```

```{r}
#Here’s a complete R snippet that automatically extracts the top 30 genes by logFC for every cluster and prints them all. No manual changes needed for cluster numbers.


# Suppose your DE genes table is called `xxx`
# It should have at least these columns: feature, group, logFC

# Get all cluster IDs
clusters <- unique(xxx$group)

# Create a list to store top genes per cluster
top_genes_list <- list()

# Loop over clusters and get top 30 genes
for(clust in clusters){
  top_genes <- xxx %>%
    filter(group == clust) %>%
    arrange(desc(logFC)) %>%
    slice_head(n = 30) %>%
    pull(feature)
  
  top_genes_list[[paste0("cluster_", clust)]] <- top_genes
}

# Print top 30 genes for all clusters
for(clust in names(top_genes_list)){
  cat("=== ", clust, "===\n")
  print(top_genes_list[[clust]])
  cat("\n")
}


```
```{r}
##save the previous output

# Prepare text to save
output_text = c()

for(clust in names(top_genes_list)) {
  output_text = c(output_text,
                   paste0("=== ", clust, " ==="),
                   paste(top_genes_list[[clust]], collapse = ", "),
                   "")  # empty line for spacing
}

# Save to file
writeLines(output_text,
          "/Users/aminatasouleymanesow/Desktop/my_project/outputs/exp1/tables/top_genes_per_cluster.txt"
          )
```



```{r}
##plot new UMAP by chnaging the name of cluster to real cell_names

library(Seurat)
library(ggplot2)

library(Seurat)
library(ggplot2)

## 1. Get cluster identities as characters
clusters <- as.character(Idents(srat_filt))

## 2. Define mapping from cluster number → cell type
cluster_colors <- c(
  "0"  = "Endothelial cells",
  "1"  = "Endothelial cells",
  "2"  = "Activated Endothelial cells",
  "3"  = "Endothelial with Perivascular features",
  "4"  = "Arterial Endothelial cells",
  "5"  = "Metabolically active endothelial cells",
  "6"  = "Mural cells",
  "7"  = "B_lymphocytes",
  "8"  = "Arterial endothelial cells",
  "9"  = "Cytotoxic lymphocytes",
  "10" = "Fibroblast",
  "11" = "Lymphatic endothelial cells"
)

## 3. Map cluster numbers to cell types
cell_types <- cluster_colors[clusters]

## 4. Assign names to match cell barcodes
names(cell_types) <- colnames(srat_filt)

## 5. Add cell_type metadata
srat_filt$cell_type <- cell_types

## 6. Make sure identities are still cluster numbers (0–11)
Idents(srat_filt) <- "seurat_clusters"


## 7. Plot UMAP
p <- DimPlot(
  srat_filt,
  reduction = "umap",
  group.by = "cell_type",   # legend uses cell type names
  label = F,             # numbers (0–11) appear on the UMAP
  label.size = 4
) +
  scale_color_brewer(type = "qual", palette = "Set3")+
  theme(
    legend.position = "top",                        # legend on top
    legend.box.margin = margin(0, 0, 0, 0),
    plot.margin = margin(10, 10, 10, 10),
    legend.spacing.x = unit(2, "cm"),
    legend.text = element_text(size = 10, color="black"),
    legend.title = element_text(size = 8)
  )

## 8. Show plot
p

## 9. Optionally save larger figure
ggsave("UMAP_plot.png", plot = p, width = 12, height = 8, dpi = 300)




# OR, to save a larger figure directly
ggsave("UMAP_plot.png", plot = p, width = 10, height = 8, dpi = 300)
```
```{r}
# Check the unique clusters
#unique(Idents(srat_filt))

# Count number of clusters
length(unique(Idents(srat_filt)))
#saveRDS(srat_filt, file = "Example_srat_filt_exp1.RDS") #to save if not finish
#srat_filt <- readRDS("Example_srat_filt.RDS") #load to continue the next day

## save the data
saveRDS(
  srat_filt, 
  file = "/Users/aminatasouleymanesow/Desktop/my_project/outputs/exp1/rds/Example_srat_filt_exp1.RDS"
)
## run it later to load all 
srat_filt <- readRDS("/Users/aminatasouleymanesow/Desktop/my_project/outputs/exp1/rds/Example_srat_filt_exp1.RDS")

```




