---
title: "R Notebook"
output: html_notebook

---
##############################################################################################################################
###ANALYSIS OF SYSTEMATIC SCLEROSIS DATA######################################################################################
###############################################################################################################################

###LOAD PACKAGES#####
```{r setup, include=FALSE}

##################PACKAGES

library(Seurat)
library(Matrix)
library(dplyr)
library(gprofiler2)
library(ggplot2)
library(patchwork)
library(gplots)
library(cowplot)
library(BiocManager)
library(devtools)

 #### the wd
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/mnt/nfs/WORKSP/aminata.sow/LAB_DOCS")



```






###1.load the data
```{r}
##load data using a function for all 12obj, create seurat_obj,merge to one and save it without any process
#folder
data.dir="../../tomas.gomes/processed.data/autoimm_scrna_TomasGuerreiro/Datasets/Systemic Sclerosis/GSE138669_RAW/"
# List all .h5 files
h5.files=list.files( path = data.dir,pattern = "_feature_bc_matrix\\.h5$",full.names = TRUE)

# Assign sample names SS1–SS12
sample.names=paste0("SS", seq_along(h5.files))

 # Loop: read, filter, create Seurat object, save
for (i in seq_along(h5.files)) {
  message("Processing ", sample.names[i])
 # Read raw counts
  SS.x=Read10X_h5(h5.files[i], use.names = TRUE, unique.features = TRUE) 
# defaultDrops
  iscell_dd <- defaultDrops(SS.x, expected = 5000)
 # emptyDrops
  eout=emptyDrops(SS.x, lower = 200)
  eout$FDR[is.na(eout$FDR)] <- 1
  iscell_ed=eout$FDR <= 0.01
  # metadata
  meta=data.frame(
    iscell_dd = iscell_dd,
    iscell_ed = iscell_ed,
    row.names = colnames(SS.x)
  )
  # keep cells
  keep=iscell_dd | iscell_ed
  # Create Seurat object
  SS=CreateSeuratObject(
    counts = SS.x[, keep],
    meta.data = meta[keep, ]
  )
  # Add sample name inside Seurat object
  SS$sample=sample.names[i]   
  
# Save Seurat object
  saveRDS(
    SS,
    file = paste0("data/process/SeuratObjects/Systemic_Sclerosis_in_Skin/", sample.names[i], ".rds")
  )
}

##merge in one seurat obj
# Folder with Seurat objects
seurat.dir="data/process/SeuratObjects/Systemic_Sclerosis_in_Skin/"
rds.files=list.files(seurat.dir,pattern = "^SS[0-9]+\\.rds$",full.names = TRUE)
# Read them into a list
SS_list=lapply(rds.files, readRDS)
# Name the list (SS1–SS12)
names(SS_list)=sub("\\.rds$", "", basename(rds.files))

# Merge
SS=merge(
  x = SS_list[[1]],
  y = SS_list[-1],
  add.cell.ids = names(SS_list),
  project = "Systemic_Sclerosis"
)
saveRDS(SS,file = "data/process/SeuratObjects/Systemic_Sclerosis_in_Skin/SS_raw.rds")

#look for the assay if no RNA seet it as RNA
SS=readRDS("data/process/SeuratObjects/SS/SS_raw.rds")
DefaultAssay(SS_obj)

#save memory
rm(eout,meta,SS,SS_list,SS.x,h5.files,i,iscell_ed,iscell_dd,keep,rds.files,sample.names)
gc(full = TRUE)
getwd()
```



###2_the qc
```{r, fig.width=10,fig.height=8}
##qc
SS[["percent.mt"]]=PercentageFeatureSet(SS,pattern = "^MT-")
VlnPlot(SS,features = c("nCount_RNA","nFeature_RNA","percent.mt"), ncol = 3,log = TRUE)
SS=subset(SS,subset=nFeature_RNA>200 & nFeature_RNA<6000 & percent.mt<15)

```




###3-statistics
```{r}
##norm, fvf,scale,runpca
SS=NormalizeData(SS)
SS=FindVariableFeatures(SS)
SS=ScaleData(SS,vars.to.regress = c("nCount_RNA","percent.mt"),features = VariableFeatures(object = SS))
SS=RunPCA(SS, features = VariableFeatures(object = SS))
ElbowPlot(SS, ndims = 50, reduction = "pca")
SS=RunUMAP(SS, dims = 1:30)
DimPlot(SS,reduction = "umap", label = TRUE)

```


###4-integration
```{r}
##integration
library(harmony)
SS =RunHarmony(SS,group.by.vars = "sample",orig.reduction = "pca",dims.use = 1:30  )
SS[["RNA"]]=JoinLayers(SS[["RNA"]])
SS = RunUMAP(SS, reduction = "harmony", dims= 1:30, reduction.name = "umap.harmony")
SS=FindNeighbors(SS,reduction= "harmony",dims = 1:30)


#for the resolution

for (res in seq(0.2, 1, by = 0.1)) {
  SS=FindClusters(SS, resolution = res)
  colname=paste0("res_", res)
  SS[[colname]]=SS$seurat_clusters
}
res_cols=grep("^res_", colnames(SS@meta.data), value = TRUE)
for (res in res_cols) {
  p=DimPlot(SS, group.by = res, label = TRUE, reduction = "umap.harmony") +
       ggtitle(paste("Resolution:", res))
  print(p)
  readline(prompt="Press [Enter] to see the next resolution...")
}

#save all
pdf("output/SS/All_resolutions_UMAP.pdf", width = 6, height = 5)
for (res in res_cols) {
  p <- DimPlot(SS, group.by = res, label = TRUE, reduction = "umap.harmony") +
       ggtitle(paste("Resolution:", res))
  print(p)
}
dev.off()


#save 
p=DimPlot(SS,group.by = "res_0.8",label = TRUE,reduction = "umap.harmony" )+ ggtitle("Resolution: 0.8") +NoLegend()+
 labs(x = "UMAP.h", y = "UMAP.h") 
ggsave(filename = "output/SS/SS_resolution.pdf",plot = p,width = 13,height = 8,dpi = 300)



```


###5-clusters and markers
```{r}
###clusters

SS=FindNeighbors(SS,reduction= "harmony",dims = 1:30)
SS=FindClusters(SS_obj, resolution = 0.8,cluster.name = "harmony_clusters")
#markers
SS_markers=FindAllMarkers(SS,only.pos = TRUE,min.pct = 0.25, logfc.threshold = 0.25)
SS_markers=SS_markers %>% filter(p_val_adj < 0.05, abs(avg_log2FC) > 0.25)



```







###6-Annotation


```{r}
genes = c(
  # Differentiating keratinocytes (suprabasal)
  "KRT1", "KRT2",

  # Basal / activated keratinocytes
  "KRT14", "KRT5", "KRT17", "KRT6A", "KRT6B",

  # Terminal keratinocytes
  "LOR", "FLG", "IVL",

  # Cornified envelope
  "SPRR2G",

  # Fibroblasts
  "SFRP2", "COMP", "APOD", "APOE", "POSTN", "ANGPTL7", "COCH", "ASPN",

  # CD4 T cells
  "CD4", "TCF7", "SELL", "CD3D", "CD3E", "TRAC",
  
  # CD8 T cells
  "CD8A", "CD8B", "GZMB",

  # B cells
  "MS4A1", "CD79A", "CD79B", 
  
  # plasma cells
  "MZB1", "JCHAIN",
  
  # mon/mac
  "CD14", "CD36", "FCGR1A", "LYZ", "CD68", "CLEC9A", "CSF1R",

  # NK cells
  "GNLY","NKG7",

  # Dendritic 
  "CD1C", "HLA-DRA",

  # Macrophages 
  "CCL3", "APOC1",

  # Mast cells
  "TPSAB1", "FTH1",

  # Pericytes:Mural cells
  "RGS5", "STEAP4", "RERGL", "CXCR4",

  # Smooth muscle cells
  "DES", "TAGLN",

  # Neural / Schwann-related
  "PLP1", "PMP22", "MPZ", "MBP",

  # Proliferating cells
  "MKI67",

  # Melanocytes
  "TYRP1", "PMEL",

  # Preadipocytes
  "APMAP",

  # Endothelial cells
  "PECAM1", "VWF", "RAMP2", "CLDN5", 
  
  # Lymphatic endothelial cells
  "CCL21", "PROX1", "LYVE1",

  # Secretory cells
  "KRT19", "SNORC", "CALML5"
)

p <- DotPlot(
  SS,
  features = genes,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  group.by = "harmony_clusters"
) + RotatedAxis()

p <- p + theme(
  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9, face = "bold"),
  axis.text.y = element_text(size = 9, face = "bold")
)
#save
ggsave(filename = "output/SS/SS_cluster.pdf", plot = p, width = 13, height = 8)



```


```{r}
###use feature plot
l = FeaturePlot(SS,features = unique(genes), combine = F, order = T, reduction = "umap.harmony")
names(l) = unique(genes)

```
    
    
    
    
```{r}
#------cluster_specifique_name

##1celltype
Idents(SS)="harmony_clusters"
cluster_name_x=c(
  "0"  = "Suprabasal Keratinocyte_0" ,
  "1"  = "Basal Keratinocyte_1"    ,
  "2"  = "Basal Keratinocyte_2"            ,
  "3"  = "Mural Cells_3"      ,
  "4"  = "Fibroblasts_4"    ,
  "5"  = "Endothelial Cells_5"            ,
  "6"  = "Fibroblasts_6"          ,
  "7"  = "Smooth Muscle Cells_7"               ,
  "8"  = "Endothelial Cells_8"                ,
  "9"  = "Fibroblasts_9"              ,
  "10" = "CD4_10"        ,
  "11" = "Basal Keratinocyte_11"           ,
  "12" = "Suprabasal Keratinocyte_12"    ,
  "13" = "Dendritic Cells_13"           ,
  "14" = "Suprabasal Keratinocyte_14"             ,
  "15" = "Fibroblasts_15"            ,
  "16" = "Macrophages_16"          ,         
  "17" ="Basal Keratinocyte_17"  ,
  "18" ="Secretory Cells_17"  ,
  "19" ="Smooth Muscle Cells_19"  ,
  "20" ="CD8_20"  ,
  "21" ="Schwann Cells_21"  ,
  "22" = "Suprabasal Keratinocyte_22",
  "23" = "Mast Cells_23",
  "24" = "Melanocytes_24",
  "25" = "Lymphatic Endothelial_25"
 )

SS = RenameIdents(SS, cluster_name_x)
SS$CellType = Idents(SS)

p <- DotPlot(
  SS,
  features = genes,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  group.by = "CellType"
) + RotatedAxis()

p <- p + theme(
  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9, face = "bold"),
  axis.text.y = element_text(size = 9, face = "bold")
)
#save
ggsave(filename = "output/SS/SS_cluster_name.pdf", plot = p, width = 14, height = 10)


```
    
    
    
                       

```{r}

#------umap-----

##1celltype
Idents(SS)="harmony_clusters"
cluster_name=c(
  "0"  = "Suprabasal Keratinocyte" ,
  "1"  = "Basal Keratinocyte"    ,
  "2"  = "Basal Keratinocyte"            ,
  "3"  = "Mural Cells"      ,
  "4"  = "Fibroblasts"    ,
  "5"  = "Endothelial Cells"            ,
  "6"  = "Fibroblasts"          ,
  "7"  = "Smooth Muscle Cells"               ,
  "8"  = "Endothelial Cells"                ,
  "9"  = "Fibroblasts"              ,
  "10" = "CD4"        ,
  "11" = "Basal Keratinocyte"           ,
  "12" = "Suprabasal Keratinocyte"    ,
  "13" = "Dendritic Cells"           ,
  "14" = "Suprabasal Keratinocyte"             ,
  "15" = "Fibroblasts"            ,
  "16" = "Macrophages"          ,         
  "17" ="Basal Keratinocyte"  ,
  "18" ="Secretory Cells"  ,
  "19" ="Smooth Muscle Cells"  ,
  "20" ="CD8"  ,
  "21" ="Schwann Cells"  ,
  "22" = "Suprabasal Keratinocyte",
  "23" = "Mast Cells",
  "24" = "Melanocytes",
  "25" = "Lymphatic Endothelial"  
)

SS=RenameIdents(SS, cluster_name)
SS$Major_Celltype=Idents(SS)

##2color
celltype_cols = c(
 "Basal Keratinocyte"       = "#9467bd",
  "Suprabasal Keratinocyte" = "brown2",
  "Fibroblasts"             = "cyan",
  "Lymphatic Endothelial"   = "mediumorchid1",
  "Mural Cells"             = "#1F78B4",
  "Smooth Muscle Cells"     = "lightpink2",
  "CD4"                     = "olivedrab2",
  "CD8"                     = "tomato",
  "Dendritic Cells"         = "yellow3",
  "Macrophages"             = "orangered",
  "Mast Cells"              = "#FDBF6F",
  "Schwann Cells"           = "plum3",
  "Melanocytes"             = "orangered4",
  "Secretory Cells"         = "salmon3",
  "Endothelial Cells"       = "#E31A1C"
)

colnames(Embeddings(SS, "umap.harmony"))
##3 center
umap_df <- as.data.frame(Embeddings(SS, "umap.harmony"))
umap_df$Major_Celltype <- SS$Major_Celltype

centers <- aggregate(
  cbind(umapharmony_1, umapharmony_2) ~ Major_Celltype,
  data = umap_df,
  FUN = median
)
##plot
fig1a = ggplot(umap_df, aes(umapharmony_1, umapharmony_2, color = Major_Celltype)) +
  geom_point(size = 0.3) +
  scale_color_manual(values = celltype_cols) +
  geom_label_repel(
    data = centers,
    aes(x = umapharmony_1, y = umapharmony_2, label = Major_Celltype),
    inherit.aes = FALSE,
    fill = "white",
    color = "black",
    size = 5,
    box.padding = 0.4,
    label.size = 0.25,
    segment.color = NA
  ) +
  theme_classic() +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none"
  ) +
  labs(x = "UMAP.h", y = "UMAP.h")
fig1a

ggsave(filename = "output/SS/SS_CellType.pdf", plot = fig1a, width = 12, height = 10)


```





```{r}

#plot with markers...........
p <- DotPlot(
  SS,
  features = genes,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  group.by = "Major_Celltype"
) + RotatedAxis()

p <- p + theme(
  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9, face = "bold"),
  axis.text.y = element_text(size = 9, face = "bold")
)
ggsave(filename = "output/SS/SS_markers.pdf", plot = p, width = 14, height = 8)

```











###7Correlation
```{r}
##correlation with the cells
# 1️⃣ Set identities to cell types
Idents(SS) <- "Major_Celltype"

# sanity check
levels(Idents(SS))
# should show cell type names, NOT numbers

# 2️⃣ Average expression per cell type
av.expSS <- AverageExpression(
  SS,
  assays = "RNA",
  slot = "data"
)$RNA
# rows = genes, columns = cell types

# 3️⃣ Cell-type correlation matrix
correlation_matrixSS <- cor(
  as.matrix(av.expSS),
  use = "pairwise.complete.obs"
)

# safety cleanup
correlation_matrixSS[is.na(correlation_matrixSS)]=0

# 4️⃣ Save heatmap
pdf(
  file = "output/SS/SS_correlation.pdf",
  width = 13,
  height = 10
  
)

pheatmap(
  correlation_matrixSS,
  clustering_method = "ward.D2",
  fontsize_row = 9,
  fontsize_col = 9
)

dev.off()

```



###8 Class Major_Celltype with family

```{r}
#-------
#EXTRACT
unique(SS$Major_Celltype)

SS$General <- recode(SS$Major_Celltype,
  "Fibroblasts"                  = "Fibroblasts",
  " Mast Cells"                  ="Mast Cells",
  "Schwann Cells"                ="Glial Cells",
  "Dendritic Cells"              ="Mono/Mac",
  "Secretory Cells"              ="Epithelial Cells",
  "Mural Cells"                  ="Mural Cells",
  "CD8"                          ="CD8",
  "CD4"                          ="CD4",
  "Smooth Muscle Cells"          = "Smooth Muscle Cells",
  "Endothelial Cells"            = "Endothelial Cells",
  "Lymphatic Endothelial"       = "Endothelial Cells",
  "Melanocytes"                  = "Melanocytes",
  "Suprabasal Keratinocyte"      ="Keratinocytes",
  "Basal Keratinocyte"           ="Keratinocytes",
  "Macrophages"                  = "Mono/Mac"
)
  
```




```{r}
### TLS markers that we can have in TLS 


# Define markers per group from genes_TLS.csv
germinal_center <- c("AID", "BCL6", "PAX5", "CD40LG", "AICDA", "MYC", 
                     "IRF8", "S1PR2", "ICOS", "CXCR4", "CXCR5")

inflammation <- c("TNF", "IL1B", "IL6", "IL7", "IL8", "IL12", "IL17", 
                  "IFNG", "TGFB", "CCL2", "CCL3", "CCL4", "CCL5", 
                  "ICAM1", "VCAM1", "SELE")

lymphoid_chemokines <- c("CXCL13", "CCL21", "CCL19", "CXCL12", 
                         "CXCR5", "CCR7", "CXCR4")

hev <- c("NTAN1", "MADCAM1", "CHST4", "GLYCAM1", "FUT7", "CHST2", 
         "MEOX2", "TSPAN7", "ANKRD43", "ZNF280C")

fdc <- c("CD21", "CD23", "CR1", "CR2", "CD35", "FDCSP", 
         "CXCL13", "CD54", "ICAM1", "FCER2")

# Combine all markers in order
markers <- unique(c(germinal_center, inflammation, 
                    lymphoid_chemokines, hev, fdc))

# Filter to genes present in your Seurat object
markers <- markers[markers %in% rownames(SS)]

# Build group vector in same order
marker_groups <- case_when(
  markers %in% germinal_center    ~ "Germinal Center",
  markers %in% inflammation       ~ "Inflammation & Cytokines",
  markers %in% lymphoid_chemokines ~ "Lymphoid Chemokines",
  markers %in% hev                ~ "HEV",
  markers %in% fdc                ~ "FDC"
)
names(marker_groups) <- markers

# Group colors
group_cols <- c(
  "Germinal Center"         = "#2166AC",
  "Inflammation & Cytokines"= "#D6604D",
  "Lymphoid Chemokines"     = "#35978F",
  "HEV"                     = "#8073AC",
  "FDC"                     = "#E08214"
)

# Extract expression and percent data
Idents(SS) <- "General"
DefaultAssay(SS) <- "RNA"
expr_mat <- GetAssayData(SS, layer = "data")

percent_mat <- sapply(levels(Idents(SS)), function(ct) {
  cells <- WhichCells(SS, idents = ct)
  Matrix::rowMeans(expr_mat[markers, cells, drop = FALSE] > 0) * 100
})
percent_mat <- as.matrix(percent_mat)

avg_exp <- AverageExpression(
  SS,
  features = markers,
  assays = "RNA",
  layer = "data",
  return.seurat = FALSE
)$RNA

exp_mat <- as.matrix(avg_exp[markers, colnames(percent_mat)])
exp_mat[is.infinite(exp_mat)] <- NA

keep <- rowSums(is.na(exp_mat)) < ncol(exp_mat)
exp_mat <- exp_mat[keep, ]
percent_mat <- percent_mat[keep, ]
marker_groups <- marker_groups[rownames(exp_mat)]

exp_mat[is.na(exp_mat)] <- 0
mode(exp_mat) <- "numeric"
exp_mat_scaled <- log1p(exp_mat)
exp_mat_scaled <- t(scale(t(exp_mat_scaled)))
exp_mat_scaled[is.na(exp_mat_scaled)] <- 0

# Color function
q <- quantile(exp_mat_scaled, c(0.05, 0.5, 0.95))
col_fun <- circlize::colorRamp2(q, c("navy", "white", "firebrick"))

# Bubble cell function
cell_fun <- function(j, i, x, y, w, h, fill) {
  grid::grid.circle(
    x = x, y = y,
    r = (percent_mat[i, j] / 100) * 0.45 * min(grid::unit.c(w, h)),
    gp = grid::gpar(fill = col_fun(exp_mat_scaled[i, j]), col = "black")
  )
}

# Column annotation
celltypes <- colnames(exp_mat_scaled)
cols <- grDevices::colorRampPalette(
  RColorBrewer::brewer.pal(8, "Set2")
)(length(celltypes))
names(cols) <- celltypes

column_ha <- ComplexHeatmap::HeatmapAnnotation(
  celltype = celltypes,
  col = list(celltype = cols),
  show_annotation_name = FALSE
)

# Row annotation
row_ha <- ComplexHeatmap::rowAnnotation(
  Group = marker_groups,
  col = list(Group = group_cols),
  annotation_width = unit(3, "mm"),
  show_annotation_name = FALSE,
  annotation_legend_param = list(
    Group = list(
      title = "TLS genes",
      title_gp = grid::gpar(fontsize = 10, fontface = "bold"),
      labels_gp = grid::gpar(fontsize = 9)
    )
  )
)

# Heatmap
ht <- ComplexHeatmap::Heatmap(
  exp_mat_scaled,
  name = "Expression",
  col = col_fun,
  rect_gp = grid::gpar(type = "none"),
  cell_fun = cell_fun,
  row_names_gp = grid::gpar(fontsize = 12, fontface = "bold"),
  column_names_gp = grid::gpar(fontsize = 10, fontface = "bold"),
  column_names_rot = 90,
  border = TRUE,
  top_annotation = column_ha,
  left_annotation = row_ha,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  row_split = marker_groups,
  row_title_gp = grid::gpar(fontsize = 10, fontface = "bold"),
  row_gap = unit(2, "mm")
)

pdf("output/SS/TLS_markers.pdf",
    width = 8, height = 10)
ComplexHeatmap::draw(ht, merge_legend = TRUE)
dev.off()



```






```{r}

#pyscenic
#####for pyscenic 
expr <- GetAssayData(SS, assay = "RNA", layer = "counts")

writeMM(expr, "/mnt/nfs/WORKSP/aminata.sow/LAB_DOCS/GRN_SCENIC/SS/input/matrix.mtx")

write.table(rownames(expr),
            file = "/mnt/nfs/WORKSP/aminata.sow/LAB_DOCS/GRN_SCENIC/SS/input/genes.tsv",
            quote = FALSE,
            row.names = FALSE,
            col.names = FALSE)

write.table(colnames(expr),
            file = "/mnt/nfs/WORKSP/aminata.sow/LAB_DOCS/GRN_SCENIC/SS/input/barcodes.tsv",
            quote = FALSE,
            row.names = FALSE,
            col.names = FALSE)

```





###save the final meta.data
```{r}

keep_cols <- c(
  "orig.ident",
  "nCount_RNA",
  "nFeature_RNA",
  "sample",
  "harmony_clusters",
  "CellType",
  "Major_Celltype",
  "General"
)

SS@meta.data <- SS@meta.data[, keep_cols]



# csv
write.csv(SS@meta.data, 
          file = "data/process/SeuratObjects/SS/SS_obj.metadata.csv",
          row.names = TRUE)

##save
saveRDS(SS, file = "data/process/SeuratObjects/SS/SS_process.rds")

## run it later to load all 
SS = readRDS("data/process/SeuratObjects/SS/SS_process.rds")



```








