---
title: "R Notebook"
output: html_notebook
---
################################################################################################################################
#####ANALYSE OF PANCREAS TYPE 1 DIABETES#######################################################################################
################################################################################################################################

```{r  setup, include=FALSE}
##################PACKAGES
library(Seurat)
library(Matrix)
library(dplyr)
library(gprofiler2)
library(ggplot2)
library(patchwork)
library(gplots)
library(cowplot)
library(BiocManager)
library(devtools)


 #### the wd
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/mnt/nfs/WORKSP/aminata.sow/LAB_DOCS")

```



###1 LOAD the data
```{r}
##load the data and set only the T1D
T1D=readRDS("../../tomas.gomes/processed.data/autoimm_scrna_TomasGuerreiro/Datasets/Pancreas Type 1 Diabetes/Pancreas Type 1 Diabetes.rds")

# check default assay
DefaultAssay(T1D)
# if not RNA, set as RNA
DefaultAssay(T1D) = "RNA"

setT1D = c("T1D_ 1","T1D_ 2","T1D_ 3","T1D_ 4","T1D_ 5","T1D_ 6","T1D_ 7","T1D_ 8","T1D_ 9")
T1D = subset (T1D, subset = disease_id %in% setT1D)
saveRDS (T1D,file = "data/process/SeuratObjects/T1Diabetes/T1D_raw.rds")

```


###12-FOR THE QC
```{r}
##load and process
T1D[["percent.mt"]]=PercentageFeatureSet(T1D, pattern = "^MT-")
Idents(T1D)="x"
T1D$x="All"
VlnPlot(T1D, features = c("nCount_RNA","nFeature_RNA","percent.mt"), ncol = 3, log = TRUE, group.by = "x")
T1D=subset(T1D, subset=nFeature_RNA >300 & nFeature_RNA <7000 & percent.mt<10)


```


###3 statistics
```{r}
##norm, fvf,scale,runpca

T1D=NormalizeData(T1D)
T1D=FindVariableFeatures(T1D)
T1D=ScaleData(T1D,vars.to.regress = c("nCount_RNA","percent.mt"),features = VariableFeatures(object = T1D))
T1D=RunPCA(T1D, features = VariableFeatures(object = T1D))
ElbowPlot(T1D, ndims = 50, reduction = "pca")
T1D=RunUMAP(T1D, dims = 1:30)
DimPlot(T1D,reduction = "umap", label = TRUE)

```


###4.integration
```{r}

#----------
library(harmony)
T1D=RunHarmony(T1D,group.by.vars = "sample",orig.reduction = "pca",dims.use = 1:30  )
T1D = RunUMAP(T1D, reduction = "harmony", dims= 1:30, reduction.name = "umap.harmony")


#for the resolution
T1D=FindNeighbors(T1D,reduction= "harmony",dims = 1:30)
for (res in seq(0.2, 1, by = 0.1)) {
  T1D=FindClusters(T1D, resolution = res)
  colname=paste0("res_", res)
  T1D[[colname]]=T1D$seurat_clusters
}
res_cols=grep("^res_", colnames(T1D@meta.data), value = TRUE)
for (res in res_cols) {
  p=DimPlot(T1D, group.by = res, label = TRUE, reduction = "umap.harmony") +
       ggtitle(paste(res))
  print(p)
  readline(prompt="Press [Enter] to see the next resolution...")
  
}

#save all
pdf("output/T1D/All_resolutions_UMAP.pdf", width = 6, height = 5)
for (res in res_cols) {
  p <- DimPlot(T1D, group.by = res, label = TRUE, reduction = "umap.harmony") +
       ggtitle(paste("Resolution:", res))
  print(p)
}
dev.off()

#save 
p=DimPlot(T1D,group.by = "res_0.6",label = TRUE,reduction = "umap.harmony" )+ ggtitle("Resolution: 0.6") +NoLegend()
ggsave(filename = "output/T1D/T1D_resolution.png",plot = p,width = 12,height = 8,dpi = 300)

```


##5-cluster and markers
```{r}

###clusters
T1D=FindNeighbors(T1D,reduction= "harmony",dims = 1:30)
T1D=FindClusters(T1D, resolution = 0.6,cluster.name = "harmony_clusters")
#markers
T1Dmarkers=FindAllMarkers(T1D,only.pos = TRUE,min.pct = 0.25, logfc.threshold = 0.25)
T1Dmarkers=T1Dmarkers %>% filter(p_val_adj < 0.05, abs(avg_log2FC) > 0.25)




```





###6 annotation

```{r}
genes = c(
  # Acinar cells
  "PRSS1","CPA1","PTF1A",

  # Alpha cells
  "GCG","IRX2","ARX",

  # Beta cells
  "INS","MAFA","NKX6-1",

  # Delta cells
  "SST","LEPR",

  # Ductal cells
  "KRT19","SOX9","CFTR",

  # Endothelial cells
  "VWF",

  # Epsilon cells
  "GHRL",

  # Immune cells
  "NCF2","PTPRC","CD14", "FCGR3A","CD68", "LYZ", "CSF1R",
  
  # CD4 T cells
  "CD4", "TCF7", "SELL", "CD3D", "CD3E", "TRAC",
  
  # CD8 T cells
  "CD8A", "CD8B", "GZMB", 

  # B cells
  "MS4A1", "CD79A", "CD79B", 
  
  # plasma cells
  "MZB1", "JCHAIN",

  # PP (gamma) cells
  "PPY",
  
  # "Pericytes"
  "RGS5",

  # Stellate cells
  "COL1A1",
  #fibroblasts
  "DCN"
)

p=DotPlot(
  T1D,
  features = genes,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  split.by = NULL,
  scale = TRUE,
  scale.by = "radius",
  scale.min = NA,
  scale.max = NA,
  cluster.idents = T, 
  group.by = "harmony_clusters") + RotatedAxis() 
p
#save
ggsave(filename = "output/T1D/T1D_cluster.png", plot = p, width = 12, height = 8)

```



```{r}
l = FeaturePlot(T1D, features = unique(genes), combine = F, order = T, reduction = "umap.harmony")
names(l) = unique(genes)
```









```{r}
#------cluster_specifique_name
##1celltype
Idents(T1D)="harmony_clusters"
cluster_name_x=c(
  "0"  = "Ductal Cells_0" ,
  "1"  = "Acinar Cells_1"    ,
  "2"  = "Alpha Cells_2"            ,
  "3"  = "Acinar Cells_3"      ,
  "4"  = "Alpha Cells_4"    ,
  "5"  = "Delta Cells_5"            ,
  "6"  = "Acinar Cells_6"            ,
  "7"  = "Endothelial Cells_7"            ,
  "8"  = "Fibroblasts_8"             ,
  "9"  = "Acinar Cells_9"               ,
  "10" = "Alpha Cells_10"        ,
  "11" = "Ductal Cells_11"    ,
  "12" = "Mural Cells_12"    ,
  "13" = "Macrophages_13"           ,
  "14" = "Acinar Cells_14"             ,
  "15" = "Ductal Cells_15"  ,
  "16" ="Acinar Cells_16",
  "17" ="Acinar Cells_17",
  "18" = "Fibroblasts_18"
  
)

T1D=RenameIdents(T1D, cluster_name_x)
T1D$CellType=Idents(T1D)

#plot
p=DotPlot(
  T1D,
  features = genes,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  split.by = NULL,
  scale = TRUE,
  scale.by = "radius",
  scale.min = NA,
  scale.max = NA,
  cluster.idents = T, 
  group.by = "CellType") + RotatedAxis() 
p
#save
ggsave(filename = "output/T1D/T1D_cluster_name.png", plot = p, width = 12, height = 8)

#View(T1D@meta.data)



```






```{r}


##1celltype
Idents(T1D)="harmony_clusters"
cluster_name=c(
 "0"  = "Ductal Cells" ,
  "1"  = "Acinar Cells"    ,
  "2"  = "Alpha Cells"            ,
  "3"  = "Acinar Cells"      ,
  "4"  = "Alpha Cells"    ,
  "5"  = "Delta Cells"            ,
  "6"  = "Acinar Cells"            ,
  "7"  = "Endothelial Cells"            ,
  "8"  = "Fibroblasts"             ,
  "9"  = "Acinar Cells"               ,
  "10" = "Alpha Cells"        ,
  "11" = "Ductal Cells"    ,
  "12" = "Mural Cells"    ,
  "13" = "Macrophages"           ,
  "14" = "Acinar Cells"             ,
  "15" = "Ductal Cells"  ,
  "16" ="Acinar Cells",
  "17" ="Acinar Cells",
  "18" = "Fibroblasts"      
             
)

T1D=RenameIdents(T1D, cluster_name)
T1D$Major_Celltype=Idents(T1D)
##2color
celltype_cols=c(
  "Acinar Cells"            = "#D73027",  
  "Alpha Cells"             = "#4575B4", 
  "Ductal Cells"            = "#FDAE61",  
  "Delta Cells"             = "#762A83",
  "Endothelial Cells"       = "#66A61E",
  "Stellate Cells"          = "#FFD92F",
  "Macrophages"             = "tomato",
  "Fibroblasts"             ="blue",
  "Mural Cells"             ="cyan"
  )

colnames(Embeddings(T1D, "umap.harmony"))
##3 center
umap_df <- as.data.frame(Embeddings(T1D, "umap.harmony"))
umap_df$Major_Celltype <- T1D$Major_Celltype

centers <- aggregate(
  cbind(umapharmony_1, umapharmony_2) ~ Major_Celltype,
  data = umap_df,
  FUN = median
)
##plot
fig1a = ggplot(umap_df, aes(umapharmony_1, umapharmony_2, color = Major_Celltype)) +
  geom_point(size = 0.3) +
  scale_color_manual(values = celltype_cols) +
  geom_label_repel(
    data = centers,
    aes(x = umapharmony_1, y = umapharmony_2, label = Major_Celltype),
    inherit.aes = FALSE,
    fill = "white",
    color = "black",
    size = 4,
    box.padding = 0.4,
    label.size = 0.25,
    segment.color = NA
  ) +
  theme_classic() +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none"
  ) +
  labs(x = "umapharmony_1", y = "umapharmony_2")
fig1a
ggsave(ggsave(filename = "output/T1D/T1D_cellType.png", plot = fig1a, width = 12, height = 8))

```








##6Plot with markers and Correlation
```{r}

## ===============================
## ComplexHeatmap Dot Heatmap
## ===============================

## ===============================
## ComplexHeatmap Dot Heatmap
## ===============================

library(Seurat)
library(dplyr)
library(Matrix)
library(circlize)
library(ComplexHeatmap)
library(viridis)
library(grid)
library(plyr)
library(pheatmap)



# -------------------------------
# 1️⃣ Correlation heatmap (optional)
# -------------------------------

# Average expression per cluster (SCT)
av.expSS <- AverageExpression(
  T1D,
  assays = "RNA",
  slot = "data"
)$RNA

# Correlation matrix
correlation_matrixSS <- cor(
  as.matrix(av.expSS),
  use = "pairwise.complete.obs"
)

# Replace NA / NaN
correlation_matrixSS[is.na(correlation_matrixSS)] <- 0
correlation_matrixSS[is.nan(correlation_matrixSS)] <- 0

# Add tiny jitter to avoid identical breaks
set.seed(1)
epsilon <- 1e-10
correlation_matrixSS_jitter <- correlation_matrixSS +
  matrix(runif(length(correlation_matrixSS), 0, epsilon),
         nrow = nrow(correlation_matrixSS))

# Save correlation heatmap as PNG

png(
  filename = "output/T1D/T1D_correlation.png",
  width = 3100,
  height = 2200,
  res = 300
)
#---
pheatmap(
  correlation_matrixSS_jitter,
  clustering_method = "ward.D2",
  fontsize_row = 8,
  fontsize_col = 8
)
dev.off()
# -------------------------------
# 2️⃣ Dot heatmap (ComplexHeatmap)
# -------------------------------



T1D$celltype <- mapvalues(as.character(Idents(T1D)), 
                          from = names(cluster_name), 
                          to = cluster_name)
Idents(T1D) <- "celltype"

# Expression and percent matrices
DefaultAssay(T1D) <- "RNA"
expr_mat <- GetAssayData(T1D, layer = "data")

percent_mat <- sapply(levels(Idents(T1D)), function(ct) {
  cells <- WhichCells(T1D, idents = ct)
  Matrix::rowMeans(expr_mat[genes, cells] > 0) * 100
})
percent_mat <- as.matrix(percent_mat)

avg_exp <- AverageExpression(T1D, features = genes, assays = "RNA",
                             layer = "data", return.seurat = FALSE)$RNA
exp_mat <- as.matrix(avg_exp[genes, colnames(percent_mat)])

# Clean Inf / NA
exp_mat[is.infinite(exp_mat)] <- NA
keep <- rowSums(is.na(exp_mat)) < ncol(exp_mat)
exp_mat <- exp_mat[keep, ]
percent_mat <- percent_mat[keep, ]
exp_mat[is.na(exp_mat)] <- 0
mode(exp_mat) <- "numeric"

# Color function
q <- quantile(exp_mat, c(0.05, 0.5, 0.95))
col_fun <- colorRamp2(q, c("navy", "white", "firebrick"))

# Dot function
cell_fun <- function(j, i, x, y, w, h, fill) {
  grid.circle(
    x = x, y = y,
    r = (percent_mat[i, j] / 100) * 0.45 * min(unit.c(w, h)),
    gp = gpar(fill = col_fun(exp_mat[i, j]), col = "black")
  )
}

# Column annotation
celltypes <- colnames(exp_mat)
cols <- viridis(length(celltypes))
names(cols) <- celltypes
column_ha <- HeatmapAnnotation(celltype = celltypes, col = list(celltype = cols))

# Create heatmap object

# log1p transform (log(1+x)) to bring values to reasonable range
exp_mat_scaled=log1p(exp_mat)

# optional: z-score per gene (row)
exp_mat_scaled=t(scale(t(exp_mat_scaled)))
exp_mat_scaled[is.na(exp_mat_scaled)]= 0

ht=Heatmap(
  exp_mat_scaled,
  name = "Expression",
  col = col_fun,   # you can regenerate col_fun for scaled values
  rect_gp = gpar(type = "none"),
  cell_fun = cell_fun,
  row_names_gp = gpar(fontsize = 6),
  column_names_gp = gpar(fontsize = 8, rot = 45),
  border = TRUE,
  top_annotation = column_ha,
  row_km = 4
)

# -------------------------------
# 3️⃣ Save ComplexHeatmap as PNG
# -------------------------------

png(filename = "output/T1D/T1D_markers.png",
    width = 3100, height = 2200, res = 300)
draw(ht)
dev.off()


```




##markers that we can have in TLS 
```{r, fig.width=12, fig.height=8}
#----------
markers <- c(
  "AID", "AICDA", "BCL6", "PAX5", "MYC", "IRF8","CD40LG", "ICOS","S1PR2", "CXCR4", "CXCR5", "CCR7","TNF", "IL1B", "IL6", "IL7", "IL8", "IL12", "IL17", "IFNG", "TGFB","CCL2", "CCL3", "CCL4", "CCL5","CXCL12", "CXCL13", "CCL19", "CCL21","ICAM1", "VCAM1", "SELE", "CD54","MADCAM1", "CHST4", "GLYCAM1", "FUT7", "CHST2","MEOX2", "TSPAN7", "ANKRD43", "ZNF280C","CD21", "CD23", "CR1", "CR2", "CD35","FDCSP", "FCER2", "NTAN1")

p <- DotPlot(
  T1D,
  features = markers,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  group.by = "Major_Celltype"
) + RotatedAxis()

p <- p + theme(
  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9, face = "bold"),
  axis.text.y = element_text(size = 9, face = "bold")
)
 ggsave(filename = "output/T1D/TLS_markers.png", plot = p, width = 12, height = 8)
 
```


###7 Class Major_Celltype with family


```{r}
#------
#extract
unique(T1D$Major_Celltype)

#
T1D$General <- recode(T1D$Major_Celltype,
                      "Ductal Cells"="Epithelial Cells" ,
                      "Acinar Cells" ="Epithelial Cells",
                      "Alpha Cells" ="Endocrine Cells" ,
                      "Fibroblasts" ="Fibroblasts",
                      "Endothelial Cells"="Endothelial Cells",
                      "Delta Cells"  ="Endocrine Cells",
                      "Mural Cells"  ="Mural Cells",
                      "Macrophages" ="Mono/Mac"
)

```







```{r}

##save


keep_cols <- c(
  "orig.ident",
  "nCount_RNA",
  "nFeature_RNA",
  "sample",
  "harmony_clusters",
  "CellType",
  "Major_Celltype",
  "General"
)

T1D@meta.data <- T1D@meta.data[, keep_cols]

#CSV 
write.csv(T1D@meta.data,file = "data/process/SeuratObjects/T1D/T1D.metadata.csv",row.names = TRUE) 
          
##rds
saveRDS(T1D, file="data/process/SeuratObjects/T1D/T1D_process.rds")
View(T1D@meta.data)

#load it
#T1D = readRDS("data/process/SeuratObjects/T1D/T1D_process.rds")




```


























