---
title: "R Notebook"
output: html_notebook
---

#####ANALAYSIS OF MULTICLEROSIS DATA#############



###LOAD THE PACKAGES 

```{r setup, include=FALSE}

##################PACKAGES
library(Seurat)
library(Matrix)
library(dplyr)
library(gprofiler2)
library(ggplot2)
library(patchwork)
library(gplots)
library(cowplot)
library(BiocManager)
library(devtools)
 #### the wd
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/mnt/nfs/WORKSP/aminata.sow/LAB_DOCS")

```






###1-LOAD THE DATA

```{r}
#######load data
MS = read.csv("../../tomas.gomes/processed.data/autoimm_scrna_TomasGuerreiro/Datasets/Multiple Sclerosis/GSE180759_expression_matrix.csv/GSE180759_expression_matrix.csv")

```


###2-CREATE SEURAT_OBJ

```{r}
##convert to matrix using sparse matrix that store non zero_values
MS_matrix  = as ( MS, "sparseMatrix")

##seurat_obj
MS = CreateSeuratObject(MS_matrix, project = "MS")
##save the raw_file 
saveRDS(MS, file = "data/process/SeuratObjects/Multiple_Sclerosis/MS_raw.rds")

```




###3-FOR THE QC

```{r, fig.width=10, fig.height=8}
#####

MS = readRDS("data/process/SeuratObjects/Multiple_Sclerosis/MS_raw.rds")
## THE QC for the cutoff to use
MS[["percent.mt"]] = PercentageFeatureSet(MS ,pattern = "^MT-")
VlnPlot(MS, features = c("nFeature_RNA","nCount_RNA", "percent.mt"),ncol = 3, log = TRUE)
MS = subset(MS, subset = nFeature_RNA >300 & nFeature_RNA < 6000 & percent.mt <15)
### to detect abnormal cells 
plot1=FeatureScatter(MS, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 = FeatureScatter(MS,feature1 = "nCount_RNA" , feature2 = "nFeature_RNA")
plot1 + plot2
ElbowPlot(MS ,ndims = 50, reduction = "pca")

```


###4-Statistics

```{r}
#Normalize,fvf,pca,scale
MS=NormalizeData(MS)
MS=FindVariableFeatures(MS)
MS=ScaleData(MS, vars.to.regress = c("nCount_RNA", "percent.mt"),features = VariableFeatures(object = MS))
MS=RunPCA(MS,features = VariableFeatures(object = MS))
MS=RunUMAP(MS,dims = 1:30)
p=DimPlot(MS, reduction = "umap",label = TRUE)
ggsave(filename = "output/Multiple_Sclerosis/MSUmap.png", plot=p, width = 12, height = 8)

#ELBOW_plot for the threshol of the clusters and neighboor
ElbowPlot(MS,ndims = 50, reduction = "pca")

#for the resolution
MS=FindNeighbors(MS,dims = 1:30)
for (res in seq(0.2, 1, by = 0.1)) {
  MS <- FindClusters(MS, resolution = res)
  colname <- paste0("res_", res)
  MS[[colname]] <- MS$seurat_clusters
}
res_cols <- grep("^res_", colnames(MS@meta.data), value = TRUE)
for (res in res_cols) {
  p <- DimPlot(MS, group.by = res, label = TRUE, reduction = "umap") +
       ggtitle(paste("Resolution:", res))
  print(p)
  readline(prompt="Press [Enter] to see the next resolution...")
}
#save all
pdf("output/MS/All_resolutions_UMAP.pdf", width = 6, height = 5)

for (res in res_cols) {
  p <- DimPlot(MS, group.by = res, label = TRUE, reduction = "umap") +
       ggtitle(paste("Resolution:", res))
  
  print(p)
}

dev.off()


# save the chosen one 
p_res03 = DimPlot(MS, group.by = "res_0.3", label = TRUE, reduction = "umap") + 
  ggtitle("Resolution: 0.3") +
  NoLegend() +
  labs(x = "UMAP.h", y = "UMAP.h")  

ggsave(filename = "output/MS/MSresolution.pdf", plot = p_res03, width = 12, height = 8, dpi = 300)


```




###5-clusters and find all markers
```{r}
##cluster......
MS=FindNeighbors(MS,reduction ="pca",dims = 1:30)
MS=FindClusters(MS, resolution = 0.3)
##markers, apply the filtering and save
MS_markers=FindAllMarkers(MS,only.pos = TRUE,min.pct = 0.25,logfc.threshold = 0.25)
MS_markers=MS_markers %>% filter(p_val_adj < 0.05, abs(avg_log2FC) > 0.25)


```

###6-Annotation based on markers genes

```{r}
genes = c(
  # CD4 T cells
  "CD4", "TCF7", "SELL", "CD3D", "CD3E", "TRAC",#TRAC,CD3E,CD3D express also in CD8 T cells
  
  # CD8 T cells
  "CD8A", "CD8B", "GZMB", 

  # B cells
  "MS4A1", "CD79A", "CD79B", 
  
  # plasma cells
  "MZB1", "JCHAIN",
  
  # mon/mac
  "CD14", "CD36", "FCGR1A", "LYZ", "CD68", "CLEC9A", "CSF1R",

  # Microglia
  "P2RY12", "TMEM119", "CX3CR1",
  "SPP1", "GPNMB", "APOE", "ITGAX", "CST7",

  # Astrocytes
  "GFAP", "AQP4", "ALDH1L1", "SLC1A2", "C3",

  # Oligodendrocytes
  "MBP", "PLP1", "MOG", "MOBP", "MAL",

  # OPCs
  "PDGFRA", "CSPG4",

  # Endothelial
  "PECAM1", "VWF", "CLDN5",
  
 

  # mUral cells
  "PDGFRB", "RGS5",
  
  # Fibroblasts
  "LUM", "DCN", "ACTA2",

  # Neurons
  "RBFOX3", "MAP2", "SNAP25"
)



```

 
 
```{r}

#########check expression to see if we need subcluster or not 
##feature plots
#l = FeaturePlot(MS,features = unique(genes), combine = F, order = T)
#names(l) = unique(genes)             
 
 #find subclusters
FeaturePlot(MS, features = c("CD4","TCF7", "SELL"), combine = F, order = T, reduction = "umap")


Idents(MS) <- MS$res_0.3
MS$seurat_clusters <- Idents(MS)

MS <- FindSubCluster(MS, cluster = c(11, 19), resolution = 0.1, graph.name = "RNA_snn")

table(MS$sub.cluster)   # should now show 18 unchanged clusters + 11_0/11_1 + 19_0/19_1 = 22 total    


P = DimPlot(MS, 
            group.by = "sub.cluster", 
            reduction = "umap", 
            label = T,
            label.size = 5) +
    labs(x = "UMAP.h", 
         y = "UMAP.h")


ggsave(filename = "output/MS/MS_sub.cluster.pdf", plot = P, width = 12, height = 8)




```
  
  
  

```{r}
p=DotPlot(
  MS,
  features = genes,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  split.by = NULL,
  scale = TRUE,
  scale.by = "radius",
  scale.min = NA,
  scale.max = NA,
  cluster.idents = T, 
  group.by = "sub.cluster") + RotatedAxis()  
    p <- p + theme(
  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9, face = "bold"),
  axis.text.y = element_text(size = 9, face = "bold")
)
p

ggsave(filename = "output/MS/MS_cluster.pdf", plot = p, width = 13, height = 10)

```







```{r, fig.width=12, fig.height=8}

##match the celltype with each cluster specifique

Idents(MS)="sub.cluster"
cluster_name_x = c(
  "0"="Oligodendrocytes_0",
  "1"="Oligodendrocytes_1",
  "2"="Oligodendrocytes_2",
  "3"="Oligodendrocytes_3",
  "4"="Oligodendrocytes_4",
  "5"="Astrocytes_5",
  "6"="Microglia_6",
  "7"="Oligodendrocytes_7",
  "8"="OPC_8",
  "9"="Neurons_9",
  "10"="Microglia_10",
  "11_0"="Endothelial Cells_11_0",
  "11_1"="CD4_11_1",
  "11_2" = "Mural Cells_11_2",
  "12"="Astrocytes_12",
  "13"="Astrocytes_13",
  "14"="Neurons_14",
  "15"="Astrocytes_15",
  "16"="Astrocytes_16",
  "17"="Microglia_17",
  "18"="Fibroblasts_18",
  "19_0"="Endothelial Cells_19_0",
  "19_1" = "CD8_19_1",
  "19_2" ="Mural Cells_19_2"
  )
MS=RenameIdents(MS, cluster_name_x)
MS$CellType = Idents(MS)
p <- DotPlot(
  MS,
  features = genes,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  group.by = "CellType"
) + RotatedAxis()

p <- p + theme(
  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9, face = "bold"),
  axis.text.y = element_text(size = 9, face = "bold")
)

#save
ggsave(filename = "output/MS/MS_cluster_name.pdf", plot = p, width = 12, height = 10)


```

 
  


```{r}

##-----umap--------------

#1-celltype for the umap
Idents(MS)="sub.cluster"
cluster_name = c(
  "0"="Oligodendrocytes",
  "1"="Oligodendrocytes",
  "2"="Oligodendrocytes",
  "3"="Oligodendrocytes",
  "4"="Oligodendrocytes",
  "5"="Astrocytes",
  "6"="Microglia",
  "7"="Oligodendrocytes",
  "8"="OPC",
  "9"="Neurons",
  "10"="Microglia",
  "11_0"="Endothelial Cells",
  "11_1" ="CD4",
  "11_2"="Mural Cells",
  "12"="Astrocytes",
  "13"="Astrocytes",
  "14"="Neurons",
  "15"="Astrocytes",
  "16"="Astrocytes",
  "17"="Microglia",
  "18"="Fibroblasts",
  "19_0" ="Endothelial Cells",
  "19_1"="CD8",
  "19_2" = "Mural Cells"
  )
MS=RenameIdents(MS, cluster_name)
MS$Major_Celltype=Idents(MS)
##2
##change cluster_name
celltype_cols=c(
  "Oligodendrocytes"      = "aquamarine3",
  "Astrocytes"            =  "#17BECF",         
  "Microglia"             = "cadetblue",
  "OPC"                   = "grey",
  "Neurons"               = "#4B2EFF",
  "CD8"                   = "tomato",            
  "Endothelial Cells"     = "#E31A1C",
  "Mural Cells"           = "#1F78B4",
  "Fibroblasts"            = "cyan",
  "CD4"                    = "olivedrab2"

)
##3 center
umap_df=as.data.frame(Embeddings(MS, "umap"))
umap_df$Major_Celltype=MS$Major_Celltype
centers <- aggregate(
  cbind(umap_1, umap_2) ~ Major_Celltype,
  data = umap_df,
  FUN = median
)
##plot
library(ggrepel)
fig1a = ggplot(umap_df, aes(umap_1, umap_2, color = Major_Celltype)) +
  geom_point(size = 0.3) +
  scale_color_manual(values = celltype_cols) +
  geom_label_repel(
    data = centers,
    aes(x = umap_1, y = umap_2, label = Major_Celltype),
    inherit.aes = FALSE,
    fill = "white",
    color = "black",
    size = 6,
    box.padding = 0.4,
    label.size = 0.25,
    segment.color = NA
  ) +
  theme_classic() +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none"
  ) +
  labs(x = "UMAP.h", y = "UMAP.h")
fig1a
ggsave(filename = "output/MS/MS_CellType.pdf", plot = fig1a, width = 12, height = 10)


```






```{r}

#plot with markers...........
p <- DotPlot(
  MS,
  features = genes,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  group.by = "Major_Celltype"
) + RotatedAxis()

p <- p + theme(
  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9, face = "bold"),
  axis.text.y = element_text(size = 9, face = "bold")
)

ggsave(filename = "output/MS/MS_markers.pdf", plot = p, width = 12, height = 8)


```





###7Correlation
```{r}

##correlation between celltype
#1 Set identities to cell types
Idents(MS) = "Major_Celltype"

#to see cellname
levels(Idents(MS))


#2 Identify highly variable genes
MS = FindVariableFeatures(MS, nfeatures = 10000)
hvg = VariableFeatures(MS)[1:5000]

#3 Average expression using HVGs
av_expMS = AverageExpression(
  MS,
  features = hvg,
  assays = "RNA",
  slot = "data"
)$RNA

#4 Cell-type correlation matrix (Spearman)
correlation_matrix <- cor(
  as.matrix(av_expMS),
  method = "spearman",
  use = "pairwise.complete.obs"
)

# clean
correlation_matrix[is.na(correlation_matrix)] = 0

#5 Save 
pdf(
  file = "output/MS/MS_correlation.pdf",
  width = 12,
  height = 10
)
library(pheatmap)
colors=colorRampPalette(c("#2166AC", "white", "#B2182B"))(100)
pheatmap(
  correlation_matrix,
  clustering_method = "ward.D2",
  color = colors,
  fontsize_row = 9,
  fontsize_col = 9
)

dev.off()
```



###8 Class Major_Celltype with family

```{r}

#EXTRACT
unique(MS$Major_Celltype)

MS$General <- recode(MS$Major_Celltype,
  "Oligodendrocytes" = "Glial Cells",
  "Endothelial Cells" = "Endothelial Cells",
  "OPC" = "Glial Cells",
  "CD8" = "CD8",
  "Astrocytes" = "Glial Cells", 
  "Fibroblasts" = "Fibroblasts", 
  "Microglia" = "Mono/Mac", 
  "Mural Cells" = "Mural Cells", 
  "Neurons" = "Neurons", 
  "CD4" =  "CD4"
)


```


##TLS Markers

```{r, fig.width=12, fig.height=8}


# Define markers per group from genes_TLS.csv
germinal_center <- c("AID", "BCL6", "PAX5", "CD40LG", "AICDA", "MYC", 
                     "IRF8", "S1PR2", "ICOS", "CXCR4", "CXCR5")

inflammation <- c("TNF", "IL1B", "IL6", "IL7", "IL8", "IL12", "IL17", 
                  "IFNG", "TGFB", "CCL2", "CCL3", "CCL4", "CCL5", 
                  "ICAM1", "VCAM1", "SELE")

lymphoid_chemokines <- c("CXCL13", "CCL21", "CCL19", "CXCL12", 
                         "CXCR5", "CCR7", "CXCR4")

hev <- c("NTAN1", "MADCAM1", "CHST4", "GLYCAM1", "FUT7", "CHST2", 
         "MEOX2", "TSPAN7", "ANKRD43", "ZNF280C")

fdc <- c("CD21", "CD23", "CR1", "CR2", "CD35", "FDCSP", 
         "CXCL13", "CD54", "ICAM1", "FCER2")

# Combine all markers in order
markers <- unique(c(germinal_center, inflammation, 
                    lymphoid_chemokines, hev, fdc))

# Filter to genes present in your Seurat object
markers <- markers[markers %in% rownames(MS)]

# Build group vector in same order
marker_groups <- case_when(
  markers %in% germinal_center    ~ "Germinal Center",
  markers %in% inflammation       ~ "Inflammation & Cytokines",
  markers %in% lymphoid_chemokines ~ "Lymphoid Chemokines",
  markers %in% hev                ~ "HEV",
  markers %in% fdc                ~ "FDC"
)
names(marker_groups) <- markers

# Group colors
group_cols <- c(
  "Germinal Center"         = "#2166AC",
  "Inflammation & Cytokines"= "#D6604D",
  "Lymphoid Chemokines"     = "#35978F",
  "HEV"                     = "#8073AC",
  "FDC"                     = "#E08214"
)

# Extract expression and percent data
Idents(MS) <- "General"
DefaultAssay(MS) <- "RNA"
expr_mat <- GetAssayData(MS, layer = "data")

percent_mat <- sapply(levels(Idents(MS)), function(ct) {
  cells <- WhichCells(MS, idents = ct)
  Matrix::rowMeans(expr_mat[markers, cells, drop = FALSE] > 0) * 100
})
percent_mat <- as.matrix(percent_mat)

avg_exp <- AverageExpression(
  MS,
  features = markers,
  assays = "RNA",
  layer = "data",
  return.seurat = FALSE
)$RNA

exp_mat <- as.matrix(avg_exp[markers, colnames(percent_mat)])
exp_mat[is.infinite(exp_mat)] <- NA

keep <- rowSums(is.na(exp_mat)) < ncol(exp_mat)
exp_mat <- exp_mat[keep, ]
percent_mat <- percent_mat[keep, ]
marker_groups <- marker_groups[rownames(exp_mat)]

exp_mat[is.na(exp_mat)] <- 0
mode(exp_mat) <- "numeric"
exp_mat_scaled <- log1p(exp_mat)
exp_mat_scaled <- t(scale(t(exp_mat_scaled)))
exp_mat_scaled[is.na(exp_mat_scaled)] <- 0

# Color function
q <- quantile(exp_mat_scaled, c(0.05, 0.5, 0.95))
col_fun <- circlize::colorRamp2(q, c("navy", "white", "firebrick"))

# Bubble cell function
cell_fun <- function(j, i, x, y, w, h, fill) {
  grid::grid.circle(
    x = x, y = y,
    r = (percent_mat[i, j] / 100) * 0.45 * min(grid::unit.c(w, h)),
    gp = grid::gpar(fill = col_fun(exp_mat_scaled[i, j]), col = "black")
  )
}

# Column annotation
celltypes <- colnames(exp_mat_scaled)
cols <- grDevices::colorRampPalette(
  RColorBrewer::brewer.pal(8, "Set2")
)(length(celltypes))
names(cols) <- celltypes

column_ha <- ComplexHeatmap::HeatmapAnnotation(
  celltype = celltypes,
  col = list(celltype = cols),
  show_annotation_name = FALSE
)

# Row annotation
row_ha <- ComplexHeatmap::rowAnnotation(
  Group = marker_groups,
  col = list(Group = group_cols),
  annotation_width = unit(3, "mm"),
  show_annotation_name = FALSE,
  annotation_legend_param = list(
    Group = list(
      title = "TLS genes",
      title_gp = grid::gpar(fontsize = 10, fontface = "bold"),
      labels_gp = grid::gpar(fontsize = 9)
    )
  )
)

# Heatmap
ht <- ComplexHeatmap::Heatmap(
  exp_mat_scaled,
  name = "Expression",
  col = col_fun,
  rect_gp = grid::gpar(type = "none"),
  cell_fun = cell_fun,
  row_names_gp = grid::gpar(fontsize = 12, fontface = "bold"),
  column_names_gp = grid::gpar(fontsize = 10, fontface = "bold"),
  column_names_rot = 90,
  border = TRUE,
  top_annotation = column_ha,
  left_annotation = row_ha,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  row_split = marker_groups,
  row_title_gp = grid::gpar(fontsize = 10, fontface = "bold"),
  row_gap = unit(2, "mm")
)

pdf("output/MS/TLS_markers.pdf",
    width = 8, height = 10)
ComplexHeatmap::draw(ht, merge_legend = TRUE)
dev.off()


```








###-Save rds file
```{r}
#csv
write.csv(MS@meta.data, 
          file = "data/process/SeuratObjects/MS//MS_Final.csv",
          row.names = TRUE)
#rds
saveRDS(MS, file = "data/process/SeuratObjects/MS/MS_process.rds")

## run it later to load all 
MS = readRDS("data/process/SeuratObjects/MS/MS_process.rds")

# Check min and max for total counts (UMIs) per cell
range(MS$nCount_RNA)

# Check min and max for unique genes per cell
range(MS$nFeature_RNA)

```




